services:
  rpc-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: rpc-agent:latest
    container_name: rpc-agent
    restart: unless-stopped
    ports:
      - "8087:8087"
    volumes:
      - ./etc:/app/etc
    environment:
      - ETCD_ENDPOINTS=10.8.0.1:2379
    networks:
      - thinktalk-net

networks:
  thinktalk-net:
    driver: bridge
