// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package agent

import (
	"context"

	"rpc-agent/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatEvent             = agent.ChatEvent
	ChatRequest           = agent.ChatRequest
	DeleteSessionRequest  = agent.DeleteSessionRequest
	DeleteSessionResponse = agent.DeleteSessionResponse
	GetHistoryRequest     = agent.GetHistoryRequest
	GetHistoryResponse    = agent.GetHistoryResponse
	ListSessionsRequest   = agent.ListSessionsRequest
	ListSessionsResponse  = agent.ListSessionsResponse
	StopRequest           = agent.StopRequest
	StopResponse          = agent.StopResponse

	Agent interface {
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (agent.Agent_ChatClient, error)
		Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
		ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
		DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
		GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

func (m *defaultAgent) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (agent.Agent_ChatClient, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

func (m *defaultAgent) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Stop(ctx, in, opts...)
}

func (m *defaultAgent) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.ListSessions(ctx, in, opts...)
}

func (m *defaultAgent) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.DeleteSession(ctx, in, opts...)
}

func (m *defaultAgent) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetHistory(ctx, in, opts...)
}
