// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package server

import (
	"context"

	"rpc-agent/agent"
	"rpc-agent/internal/logic/agent"
	"rpc-agent/internal/svc"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentServer) Chat(in *agent.ChatRequest, stream agent.Agent_ChatServer) error {
	l := agentlogic.NewChatLogic(stream.Context(), s.svcCtx)
	return l.Chat(in, stream)
}

func (s *AgentServer) Stop(ctx context.Context, in *agent.StopRequest) (*agent.StopResponse, error) {
	l := agentlogic.NewStopLogic(ctx, s.svcCtx)
	return l.Stop(in)
}

func (s *AgentServer) ListSessions(ctx context.Context, in *agent.ListSessionsRequest) (*agent.ListSessionsResponse, error) {
	l := agentlogic.NewListSessionsLogic(ctx, s.svcCtx)
	return l.ListSessions(in)
}

func (s *AgentServer) DeleteSession(ctx context.Context, in *agent.DeleteSessionRequest) (*agent.DeleteSessionResponse, error) {
	l := agentlogic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}

func (s *AgentServer) GetHistory(ctx context.Context, in *agent.GetHistoryRequest) (*agent.GetHistoryResponse, error) {
	l := agentlogic.NewGetHistoryLogic(ctx, s.svcCtx)
	return l.GetHistory(in)
}
